### ISSUE TITLE
What does `,0` at the end each line mean?

### ISSUE THREAD

**Issue by zsluedem** [r-publishing/mainnet-genesis#1]
https://github.com/r-publishing/mainnet-genesis/blob/master/wallets.txt#L3

```
11112fkGn8gH25u4zmixD1PNG1UUKEPoND3fDchhzvNdEaZdKzC8TL,959540000,0
```

Why `,0` is needed?

**Comment by Bill-Kunj** [comment]
Perhaps @tgrospic can explain this best

**Comment by tgrospic** [comment]
This is not used anymore.
https://github.com/rchain/rchain/blob/dev/wallets.txt

Initially, the last flag value `{0,1}` was used with ETH addresses to mark addresses owned by private key or by the contract.

**Comment by Bill-Kunj** [comment]
@zsluedem Please close this issue if your question has been answered
