### ISSUE TITLE
Strange number in the end

### ISSUE THREAD

**Issue by zsluedem** [r-publishing/mainnet-genesis#2]
https://github.com/r-publishing/mainnet-genesis/blob/master/rpc.wallets.txt#L128

https://github.com/r-publishing/mainnet-genesis/blob/master/rpc.wallets.txt#L12154

in the end got `1.74529124056539E+016` and `1.29336426E+016` , what does that mean ?

**Comment by Bill-Kunj** [comment]
@zsluedem This is an actual error in the generation of the file. An update will be made to remove the error.

**Comment by Bill-Kunj** [comment]
Closed by https://github.com/r-publishing/mainnet-genesis/commit/3165ec8feb05dac9bb027eb6de3bc97aa2e4acd5
