### ISSUE TITLE
Establish RPC system monitoring

### ISSUE THREAD

**Issue by Bill-Kunj** [r-publishing/mainnet-genesis#25]
RPC is currently relying on RChain best-practices for monitoring. This needs to be documented for RPC launch

**Comment by Bill-Kunj** [comment]
@momchilov is working on Grafana up/down monitoring based on http port availability

**Comment by Bill-Kunj** [comment]
This issue is now linked with RChain issue https://github.com/rchain/rchain/issues/3143

**Comment by Bill-Kunj** [comment]
This effort has transitioned to a discord bot instead of Grafana/Prometheus.

**Comment by momchilov** [comment]
Until we are comfortable with Prometheus.

**Comment by Bill-Kunj** [comment]
Resolved with https://github.com/r-publishing/rpub-bot. Closing
