### ISSUE TITLE
Question: What is the "X" value  rpc.wallets file used to calculate the value?

### ISSUE THREAD

**Issue by zsluedem** [r-publishing/mainnet-genesis#3]
As the title said.

![image](https://user-images.githubusercontent.com/13496262/158923610-06a43931-f5ed-4574-bf2d-f244191b3d46.png)

What is the "X" value ?

**Comment by Bill-Kunj** [comment]
"the total pool of RChain REV is deemed to be X"
The sum total of REV by all REV holders (from the snapshot) has been used as X.

**Comment by zsluedem** [comment]
Oh. I want the concrete number. From my calculation, it is `1060000000000153`. Just want to make sure.

**Comment by Bill-Kunj** [comment]
> Oh. I want the concrete number. From my calculation, it is `1060000000000153`. Just want to make sure.

The number I see in my spreadsheet is `1060000000000100`.
Please close if you confirm
