### ISSUE TITLE
Multi-sig public keys not working

### ISSUE THREAD

**Issue by Bill-Kunj** [r-publishing/mainnet-genesis#7]
From rchain-core:
https://github.com/rchain/rchain/issues/3647
https://github.com/rchain/rchain/issues/3362

**Comment by tgrospic** [comment]
All issues for RPC version of RNode are tracked here on RChain repo in epic issue.
- https://github.com/rchain/rchain/issues/3642

**Comment by Bill-Kunj** [comment]
@tgrospic Is the resolution to this issue fully tested?

**Comment by Bill-Kunj** [comment]
Closed due to https://github.com/rchain/rchain/issues/3642 closing
